name: Nix Build

on:
  pull_request:
  push:

jobs:
  esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create dummy .env
        run: |
          touch .env
          echo "WIFI_SSID=ssid" >> .env
          echo "WIFI_PASSWORD=password" >> .env
      - name: Build
      - run: nix build .#esp32
