name: Rust CI

on:
  pull_request:
  push:

jobs:
  esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create dummy .env
        run: |
          touch .env
          echo "WIFI_SSID=ssid" >> .env
          echo "WIFI_PASSWORD=password" >> .env
      - name: Brwap workaround
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Build
        run: nix build .#esp32
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: nix build .#backend
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: nix build .#frontend
